#!/usr/bin/env bash
# Regenerate data/abf-brands.js from the upstream AmazonBrandFilterList.
# The extension also refreshes this list at runtime once a day; this script
# just keeps the bundled snapshot current for new installs.
set -euo pipefail
cd "$(dirname "$0")/.."

curl -sfL "https://raw.githubusercontent.com/chris-mosley/AmazonBrandFilterList/main/brands.txt" -o /tmp/abf-brands.txt

python3 - <<'EOF'
import json

with open("/tmp/abf-brands.txt") as f:
    brands = [line.strip() for line in f if line.strip()]

seen, out = set(), []
for b in brands:
    k = b.lower()
    if k not in seen:
        seen.add(k)
        out.append(b)

with open("data/abf-brands.js", "w") as f:
    f.write("// Knockoff — bundled snapshot of the community-maintained allowlist from\n")
    f.write("// https://github.com/chris-mosley/AmazonBrandFilterList (%d brands).\n" % len(out))
    f.write("// Generated by scripts/update-community-list.sh — do not edit by hand.\n")
    f.write("var KO_ABF_BRANDS = " + json.dumps(out, ensure_ascii=False).replace("\n", "") + ";\n")

print(f"{len(out)} brands written to data/abf-brands.js")
EOF
